# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name=b'title')),
                ('body', models.TextField(verbose_name=b'body')),
            ],
        ),
    ]
